name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install --frozen-lockfile
    - name: Run Tests
      run: yarn test:ci
    - name: Build production artifact
      run: yarn build
    - name: Deploy to GH Pages
      run: |
        git config user.email "keshav143420@gmail.com"
        git config user.name "keshava kotri"
        git remote set-url origin https://keshav143420:${{ secrets.GITHUB_TOKEN }}@github.com/keshav143420/srtl.git
        yarn deploy